#!/bin/bash

I3_CONFIG=$HOME/.config/sway/config
# mod_key=$(sed -nre 's/^set \$mod (.*)/\1/p' ${I3_CONFIG})
mod_key=
grep "^bindsym" ${I3_CONFIG} |
  sed "s/-\(-\w\+\)\+//g;s/\$mod/${mod_key}/g;s/Mod1/Alt/g;s/exec //;s/bindsym //;s/^\s\+//;s/^\([^ ]\+\) \(.\+\)$/\2: \1/;s/^\s\+//" |
  tr -s ' ' |
  rofi -dmenu -theme ~/.config/rofi/rofikeyhint.rasi
