##########################################
# Multimedia Keys #
##########################################

# volume control
# increase
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +2%
bindsym $mod+Up exec --no-startup-id  pactl set-sink-volume @DEFAULT_SINK@ +2%

# decrease
bindsym XF86AudioLowerVolume exec --no-startup-id  pactl set-sink-volume @DEFAULT_SINK@ -2%
bindsym $mod+Down exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -2%

# mute
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym $mod+m exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle


# bind default audio keys 
bindsym XF86AudioPlay exec --no-startup-id ~/.config/i3/scripts/spotify-launcher.fish
bindsym XF86AudioNext exec --no-startup-id playerctl next
bindsym XF86AudioPrev exec --no-startup-id playerctl previous

bindsym $mod+Ctrl+space exec --no-startup-id playerctl --player=spotify play-pause
bindsym $mod+Right exec --no-startup-id playerctl --player=spotify next
bindsym $mod+Left exec --no-startup-id playerctl --player=spotify previous

# Set default sink
bindsym $mod+Shift+Up exec --no-startup-id ~/.config/i3/scripts/output-switcher headphones
bindsym $mod+Shift+Down exec --no-startup-id ~/.config/i3/scripts/output-switcher speakers

