[general]
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[terminal]
  shell = "/usr/bin/fish"

[bell]
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/bell.oga"] }
