[colors]
background = #440000
background-no-compton = #282c34
; background-alt = #282a36
background-alt = #2a2e36
foreground = #f8f8f2
foreground-alt = #f8f8f2
primary = #ffb52a
secondary = #e60053
alert = #bd2c40
underline = #99ffff
black = #000
white = #ffffff
