;;import colors
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

[settings]
; Reload when the screen configuration changes (XCB_RANDR_SCREEN_CHANGE_NOTIFY event)
screenchange-reload = false
; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.
pseudo-transparency = false

;#########
;# i3 bar
;#########
;
[bar/i3]
;monitor = ${env:MONITOR}
;wm-restack = i3

width = 100%
height = 20pt
radius = 0
; dpi = 96
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 2pt

border-bottom-size = 1
border-bottom-color = ${colors.background2}

padding-left = 0
padding-right = 1
module-margin = 1

separator = |
separator-foreground = ${colors.black}
font-0 = Jetbrains Mono Nerd Font:style:Regular:size=10;3
font-1 = Jetbrains Mono Nerd Font:style=Bold:size=10;3

modules-left = player-mpris-tail
modules-center = i3
modules-right = pulseaudio xbacklight battery htop-memory cpu xkeyboard popup-calendar powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

# tray stuff
tray-position = left
; Pad the sides of each tray icon
tray-padding = 2
; Offset the tray in the x and/or y direction
; Supports any percentage with offset
; Percentages are relative to the monitor width or height for detached trays
; and relative to the bar window (without borders) for non-detached tray.
tray-offset-x = 0
tray-offset-y = 0
tray-scale = 1.0

override-redirect = false
