[module/powermenu]
type = custom/text
content = "   "
click-left = ~/.config/i3/scripts/powermenu
format-padding = 0
content-background = ${colors.background}
content-foreground = ${colors.red}

[module/popup-calendar]
type = custom/script
exec = ~/.config/polybar/scripts/popup-calendar.sh
interval = 5
click-left = ~/.config/polybar/scripts/popup-calendar.sh --popup &
format-background = ${colors.background-alt}
format-foreground = ${colors.orange}

[module/i3]
type = internal/i3
format = <label-state>
pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-scroll = false

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;

label-mode = %icon%
label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}
;label-focused-foreground = ${colors.underline}

label-focused = %icon%
label-focused-padding = 2
label-focused-underline = ${colors.underline}
label-focused-background = #44000000

label-unfocused = %icon%
label-unfocused-padding = 2
label-unfocused-foreground = #ffffff

label-urgent = %icon%
label-urgent-padding = 2
label-urgent-foreground = #FF5555

label-visible = %icon%
label-visible-padding = 2
label-visible-foreground = #ffffff

[module/player-mpris-tail]
type = custom/script
exec = ~/.config/polybar/scripts/player-mpris-tail.py --icon-playing  --icon-paused  --icon-stopped  --icon-none  -f ' {:artist:t18:{artist}:}{:artist:: :}{:t40:{title}:} %{A1:~/.config/polybar/scripts/player-mpris-tail.py previous:}  %{A} %{A1:~/.config/polybar/scripts/player-mpris-tail.py play-pause:} {icon-reversed} %{A} %{A1:~/.config/polybar/scripts/player-mpris-tail.py next:}  %{A}'
tail = true
label = %output%
format-underline = #50fa7b

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
label-volume =  %percentage%%
label-volume-foreground = ${root.foreground}

label-muted =  muted
label-muted-foreground = #666
bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}
label-volume-underline = #8be9fd

[module/memory]
type = internal/memory
interval = 1
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
;format-underline = ${colors.underline}
label = %percentage_used%%
format-underline = #ffb86c

[module/cpu]
type = internal/cpu
interval = 1
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #ff5555

label = %percentage:2%%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/xwindow]
type = internal/xwindow
label = %title:0:80:...%
;status_command python /usr/lib/python3.9/site-packages/powerline/bindings/i3/powerline-i3.py


[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>


host = 127.0.0.1
port = 6600

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/eth]
type = internal/network
interface = eno1
interval = 3.0

;format-connected-underline = ${colors.underline}
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected =  %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 1

date = " %d/%m/%Y"
date-alt =

time = " %H:%M "
time-alt = " %H:%M "

format-underline = #ff79c6
label = %{A1:gsimplecal:} %date% %time% %{A}


[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP0
full-at = 98

format-charging = <animation-charging>  <label-charging>
format-charging-underline = ${colors.underline}

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = ${colors.underline}
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/pavolume]
type = custom/script
interval = 2
label=VOLUME:%output%
exec = ~/.config/polybar/scripts/pavolume.sh
click-right = exec pavucontrol
click-left = ~/.config/polybar/scripts/pavolume.sh --togmute
scroll-up = ~/.config/polybar/scripts/pavolume.sh --up
scroll-down = ~/.config/polybar/scripts/pavolume.sh --down
label-padding = 2
label-foreground = ${colors.white}

[module/wlan]
type = internal/network
interface = wlo1
interval = 3.0
format-connected = %{A1:rofi-wifi-menu:}<label-connected>%{A}
format-disconnected = %{A1:rofi-wifi-menu:}Disconnected%{A}
;format-disconnected = %{A1:networkmanager_dmenu:}Disconnected%{A}
;format-connected = <label-connected>
format-connected-font = 2
format-connected-prefix = " "
format-disconnected-prefix = " "
label-connected = %essid%
ramp-signal-0 = 😱
ramp-signal-1 = 😠
ramp-signal-2 = 😒
ramp-signal-3 = 😊
ramp-signal-4 = 😃
ramp-signal-5 = 😈
ramp-font = 2
format-connected-underline = #9b59f0
format-disconnected-underline = #9b59f0

